#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
#source this in .bashrc to apply to open terminals

# Check for visual monitor
if [[ "$(tty)" == *"pts"* && -z "$SSH_CLIENT" && -z "$SSH_TTY" ]]; then
    source $DIR/default.prompt
elif [[ "$(tty)" == *"pts"* ]]; then
    source $DIR/ssh.prompt
fi


# Prompt aliases
alias refactory="source $DIR/default.prompt"


# Other aliases
source $DIR/.aliases

# Path
PATH="$PATH:$DIR/bin"